export const NEXT_PUBLIC_CDP_API_KEY = process.env.NEXT_PUBLIC_CDP_API_KEY;
export const NEXT_PUBLIC_WC_PROJECT_ID = process.env.NEXT_PUBLIC_WC_PROJECT_ID;
export const NEXT_PUBLIC_PIMLICO_RPC_URL = process.env.NEXT_PUBLIC_PIMLICO_API_KEY; // Берём значение из твоего NEXT_PUBLIC_PIMLICO_API_KEY
